name: bazar_updated
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  google_maps_flutter: ^2.1.1
  flutter_local_notifications: ^9.2.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.0
  country_code_picker: ^2.0.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  provider: ^6.0.2
  another_flushbar: ^1.10.28
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splash_screen.png
    - images/bazar_logo.png
    - images/dashboard_image.png
    - images/seller_dashboard_image.png
    - images/logo.png
    - images/empty_cart.png


  fonts:
    - family: Avenir Heavy
      fonts:
        - asset: fonts/Avenir-Heavy.ttf
    - family: Avenir Book
      fonts:
        - asset: fonts/Avenir-Book.ttf
    - family: Avenir Light
      fonts:
        - asset: fonts/Avenir-Light.ttf
    - family: Avenir Roman
      fonts:
        - asset: fonts/Avenir-Roman.ttf
    - family: Avenir Black
      fonts:
        - asset: fonts/Avenir Black.ttf
    - family: Avenir Medium
      fonts:
        - asset: fonts/Avenir Medium.ttf
    - family: Custom
      fonts:
        - asset: fonts/Custom.ttf